import os
import sys
import json
import time

import requests
from requests.auth import HTTPBasicAuth
import numpy as np
import matplotlib.pyplot as plt

import logging
try:
    from logging import NullHandler
except ImportError:
    class NullHandler(logging.Handler):
        def emit(self, record):
            pass

logging.getLogger(__name__).addHandler(NullHandler())
logging.basicConfig(format='[%(asctime)s] %(levelname)s::%(module)s::%(funcName)s() %(message)s', level=logging.DEBUG)


DATA_FILE = "data.txt"
FILTER_DATA_TEMP = "filter.txt"
DEFAULT_HOST = 'http://localhost:8080'
REGISTER_URL = os.path.join(DEFAULT_HOST, 'register')
TRACK_URL = os.path.join(DEFAULT_HOST, 'rest/track')


def send_data(*, datafile):
    username, password, account_id = register()
    data = read_data(filename=datafile)
    track_id = init_transmission(data=next(data), account_id=account_id, username=username, password=password)
    auth = HTTPBasicAuth(username, password)
    locations = []
    for message in send_loop(data, auth=auth, track_id=track_id):
        locations = message['locations']
    for location in locations:
        latitude = location['latitude']
        longitude = location['longitude']
        with open(FILTER_DATA_TEMP, "a+") as file:
            file.write('{} {}\n'.format(latitude, longitude))


def send_loop(data, auth, track_id):
    for coordinates in data:
        payload = {
            "latitude": coordinates[0],
            "longitude": coordinates[1],
            "time": time.time()
        }
        url = "{}/{}".format(TRACK_URL, track_id)
        response = requests.post(url=url,
                                 auth=auth,
                                 headers={'Content-Type': 'application/json'},
                                 data=json.dumps(payload))
        yield json.loads(response.text)


def init_transmission(*, data, username, password):
    init_lat, init_lon = data
    init_time = time.time()
    payload = {
        "latitude": init_lat,
        "longitude": init_lon,
        "time": init_time
    }
    auth = HTTPBasicAuth(username, password)
    response = requests.post(url=TRACK_URL,
                             auth=auth,
                             headers={'Content-Type': 'application/json'},
                             data=json.dumps(payload))
    data = json.loads(response.text)
    track_id = data['id']
    latitude = data['locations'][0]['latitude']
    longitude = data['locations'][0]['longitude']
    with open(FILTER_DATA_TEMP, "a+") as file:
        file.write('{} {}\n'.format(latitude, longitude))
    return track_id


def register():
    username, email = generate_names()
    password = "password"
    payload = {
        "username": username,
        "password": password,
        "email": email
    }
    response = requests.post(REGISTER_URL,
                             headers={'Content-Type': 'application/json'},
                             data=json.dumps(payload))
    data = json.loads(response.text)
    account_id = data['id']
    return username, password, account_id


def generate_names():
    username = 'patryk{}'.format(str(time.time())[:-5])
    email = '{}{}'.format(username, '@email.com')
    return username, email


def read_data(*, filename):
    with open(filename, 'r') as data:
        for line in data:
            line = line.split(' ')
            x_value, y_value = line[0], line[1]
            y_value = y_value.replace('\n', '')
            yield float(x_value), float(y_value)


def clean():
    os.remove(FILTER_DATA_TEMP)


if __name__ == "__main__":
    """
    To run this script prepare database i docker container.
    You need to have prepared docker container named 'mongo'.

    If so run it by typing in your terminal:
        `docker run -p 127.0.0.1:27017:27017 mongo`
    To go inside this container you need to check container id.
    When checked run:
        `docker exec -it 613bac52578d mongo admin`

    At this step your database should be set up.
    Next run JConductor app either in Intellij
    or casually by executing:
        `java -jar <jar name>`
    on jar file generated by maven.
    """
    logging.info("Start sending data.")

    try:
        host = sys.argv[1]
    except IndexError:
        logging.debug("Working in local mode.")
        host = DEFAULT_HOST
    try:
        send_data(datafile=DATA_FILE)

        logging.info("Creating vectors.")
        x, y = zip(*[(lat, lon) for lat, lon in read_data(filename=DATA_FILE)])
        x = np.squeeze(np.asarray(x))
        y = np.squeeze(np.asarray(y))

        v, z = zip(*[(lat, lon) for lat, lon in read_data(filename=FILTER_DATA_TEMP)])
        # removing starting zeros
        v = v[2:]
        z = z[2:]
        v = np.squeeze(np.asarray(v))
        z = np.squeeze(np.asarray(z))

        logging.info("Plotting tracks.")
        plt.plot(x, y, v, z)
        plt.show()
    finally:
        logging.info("Performing clean-up.")
        clean()
