import os
import sys
import json
import time

import requests
from requests.auth import HTTPBasicAuth
import numpy as np
import matplotlib.pyplot as plt

import logging
try:
    from logging import NullHandler
except ImportError:
    class NullHandler(logging.Handler):
        def emit(self, record):
            pass

logging.getLogger(__name__).addHandler(NullHandler())
logging.basicConfig(format='[%(asctime)s] %(levelname)s::%(module)s::%(funcName)s() %(message)s', level=logging.DEBUG)


DATA_FILE = "data.txt"
FILTER_DATA_TEMP = "filter.txt"
DEFAULT_HOST = 'http://localhost:8080/rest/track'


def send_data(*, datafile, host=DEFAULT_HOST):
    data = init_transmission(datafile=datafile)
    username, password = register()
    for each in data:
        payload = {'lat': each[0], 'lon': each[1], 'position': 'CONTINUE'}
        auth = HTTPBasicAuth(username, password)
        with open(FILTER_DATA_TEMP, "a+") as file:
            file.write(r.text)
        r = requests.post(host, auth=auth, data=json.dumps(payload))


def init_transmission(*, datafile):
    data = read_data(filename=datafile)
    init_lat, init_lon = next(data)
    payload = {'lat': init_lat, 'lon': init_lon, 'position': 'START'}
    r = requests.post(host, data=json.dumps(payload))
    with open(FILTER_DATA_TEMP, "a+") as file:
        file.write(r.text)
    return data


def register():
    username, email = generate_names()
    password = "password"
    payload = {
        "username": username,
        "password": password,
        "email": email
    }
    auth = HTTPBasicAuth('user', 'pass')
    r = requests.post(host, auth=auth, data=json.dumps(payload))
    return username, password


def generate_names():
    username = 'patryk{}'.format(str(time.time())[:-6])
    email = '{}{}'.format(username, '@email.com')
    return username, email


def read_data(*, filename):
    with open(filename, 'r') as data:
        for line in data:
            line = line.split(' ')
            x_value, y_value = line[0], line[1]
            y_value = y_value.replace('\n', '')
            yield float(x_value), float(y_value)


def clean():
    os.remove(FILTER_DATA_TEMP)


if __name__ == "__main__":
    """
    To run this script prepare database i docker container.
    You need to have prepared docker container named 'mongo'.

    If so run it by typing in your terminal:
        `docker run -p 127.0.0.1:27017:27017 mongo`
    To go inside this container you need to check container id.
    When checked run:
        `docker exec -it 613bac52578d mongo admin`

    At this step your database should be set up.
    Next run JConductor app either in Intellij
    or just by executing:
        `java -jar <jar name>`
    on jar file generated by maven.
    """
    logging.info("Start sending data.")

    try:
        host = sys.argv[1]
    except IndexError:
        logging.debug("Working in local mode.")
        host = DEFAULT_HOST
    try:
        send_data(datafile=DATA_FILE, host=host)

        logging.info("Creating vectors.")
        x, y = zip(*[(lat, lon) for lat, lon in read_data(filename=DATA_FILE)])
        x = np.squeeze(np.asarray(x))
        y = np.squeeze(np.asarray(y))

        v, z = zip(*[(lat, lon) for lat, lon in read_data(filename=FILTER_DATA_TEMP)])
        v = np.squeeze(np.asarray(v))
        z = np.squeeze(np.asarray(z))

        logging.info("Plotting tracks.")
        plt.plot(x, y, v, z)
        plt.show()
    finally:
        logging.info("Performing clean-up.")
        clean()